# Generated by Django 5.1.7 on 2025-03-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('translator', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=50)),
                ('source_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sura Number')),
                ('name', models.CharField(max_length=50, verbose_name='Sura Name')),
                ('tname', models.CharField(max_length=50, verbose_name='English Transliterated Name')),
                ('ename', models.CharField(max_length=50, verbose_name='English Name')),
                ('order', models.IntegerField(verbose_name='Revelation Order')),
                ('type', models.CharField(choices=[('Meccan', 'Meccan'), ('Medinan', 'Medinan')], max_length=7, verbose_name='')),
                ('rukus', models.IntegerField(verbose_name='Number of Rukus')),
                ('bismillah', models.CharField(blank=True, max_length=50, verbose_name='Bismillah')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lemmas', to='quran.root')),
            ],
            options={
                'ordering': ['token'],
            },
        ),
        migrations.CreateModel(
            name='Aya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Aya Number')),
                ('text', models.TextField()),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayas', to='quran.sura')),
            ],
            options={
                'ordering': ['sura', 'number'],
                'unique_together': {('number', 'sura')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
                ('ename', models.CharField(blank=True, max_length=50)),
                ('translation', models.CharField(blank=True, max_length=200)),
                ('aya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.aya')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.lemma')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.root')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.sura')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('aya', 'number')},
            },
        ),
        migrations.AddField(
            model_name='root',
            name='ayas',
            field=models.ManyToManyField(through='quran.Word', to='quran.aya'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='ayas',
            field=models.ManyToManyField(through='quran.Word', to='quran.aya'),
        ),
        migrations.CreateModel(
            name='TranslatedAya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('aya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.aya')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.sura')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.qurantranslation')),
            ],
            options={
                'ordering': ['aya'],
                'unique_together': {('aya', 'translation')},
            },
        ),
    ]
