# Generated by Django 5.1.7 on 2025-03-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quran.root')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.IntegerField()),
                ('ayah', models.IntegerField()),
                ('position', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.lemma')),
            ],
        ),
    ]
